global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "crossingguard"

scrape_configs:
  -
    job_name: "traefik"
    scrape_interval: 5s
    metrics_path: "/metrics"
    scheme: http
    static_configs:
      - targets:
        - traefik:8082
