global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "crossingguard"


scrape_configs:
  -
    job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: [ "localhost:9090" ]
  -
    job_name: "traefik"
    scrape_interval: 5s
    dns_sd_configs:
    - names:
      - 'tasks.traefik'
      type: 'A'
      port: 8080
